export const PERMIT_STATUSES = {
  DRAFT: "DRAFT",
  READY_TO_SUBMIT: "READY_TO_SUBMIT",
  SUBMITTED: "SUBMITTED",
  UNDER_REVIEW: "UNDER_REVIEW",
  CORRECTIONS_NEEDED: "CORRECTIONS_NEEDED",
  RESUBMITTED: "RESUBMITTED",
  APPROVED: "APPROVED",
  PERMIT_ISSUED: "PERMIT_ISSUED",
  INSPECTION_SCHEDULED: "INSPECTION_SCHEDULED",
  INSPECTION_PASSED: "INSPECTION_PASSED",
  INSPECTION_FAILED: "INSPECTION_FAILED",
  CERTIFICATE_OF_OCCUPANCY: "CERTIFICATE_OF_OCCUPANCY",
  CLOSED: "CLOSED",
  EXPIRED: "EXPIRED",
  DENIED: "DENIED",
} as const;

export type PermitStatus = (typeof PERMIT_STATUSES)[keyof typeof PERMIT_STATUSES];

export const PERMIT_STATUS_LABELS: Record<PermitStatus, string> = {
  DRAFT: "Draft",
  READY_TO_SUBMIT: "Ready to Submit",
  SUBMITTED: "Submitted",
  UNDER_REVIEW: "Under Review",
  CORRECTIONS_NEEDED: "Corrections Needed",
  RESUBMITTED: "Resubmitted",
  APPROVED: "Approved",
  PERMIT_ISSUED: "Permit Issued",
  INSPECTION_SCHEDULED: "Inspection Scheduled",
  INSPECTION_PASSED: "Inspection Passed",
  INSPECTION_FAILED: "Inspection Failed",
  CERTIFICATE_OF_OCCUPANCY: "Certificate of Occupancy",
  CLOSED: "Closed",
  EXPIRED: "Expired",
  DENIED: "Denied",
};

export const PERMIT_STATUS_COLORS: Record<PermitStatus, string> = {
  DRAFT: "#6B7280",
  READY_TO_SUBMIT: "#3B82F6",
  SUBMITTED: "#8B5CF6",
  UNDER_REVIEW: "#F59E0B",
  CORRECTIONS_NEEDED: "#EF4444",
  RESUBMITTED: "#8B5CF6",
  APPROVED: "#10B981",
  PERMIT_ISSUED: "#10B981",
  INSPECTION_SCHEDULED: "#F59E0B",
  INSPECTION_PASSED: "#10B981",
  INSPECTION_FAILED: "#EF4444",
  CERTIFICATE_OF_OCCUPANCY: "#059669",
  CLOSED: "#6B7280",
  EXPIRED: "#9CA3AF",
  DENIED: "#DC2626",
};

// Valid status transitions
export const PERMIT_STATUS_TRANSITIONS: Record<PermitStatus, PermitStatus[]> = {
  DRAFT: ["READY_TO_SUBMIT"],
  READY_TO_SUBMIT: ["SUBMITTED", "DRAFT"],
  SUBMITTED: ["UNDER_REVIEW", "CORRECTIONS_NEEDED", "DENIED"],
  UNDER_REVIEW: ["APPROVED", "CORRECTIONS_NEEDED", "DENIED"],
  CORRECTIONS_NEEDED: ["RESUBMITTED", "DENIED"],
  RESUBMITTED: ["UNDER_REVIEW", "CORRECTIONS_NEEDED", "DENIED"],
  APPROVED: ["PERMIT_ISSUED"],
  PERMIT_ISSUED: ["INSPECTION_SCHEDULED", "EXPIRED"],
  INSPECTION_SCHEDULED: ["INSPECTION_PASSED", "INSPECTION_FAILED"],
  INSPECTION_PASSED: ["CERTIFICATE_OF_OCCUPANCY", "INSPECTION_SCHEDULED"],
  INSPECTION_FAILED: ["INSPECTION_SCHEDULED"],
  CERTIFICATE_OF_OCCUPANCY: ["CLOSED"],
  CLOSED: [],
  EXPIRED: [],
  DENIED: [],
};
