import { prisma } from "@permits/database";

/**
 * Generate a simple text-based PDF representation for a form submission.
 * For MVP, we generate a structured HTML document that can be converted to PDF.
 * In production, use @react-pdf/renderer for rich PDF layouts.
 */
export async function generateFormPDF(formId: string): Promise<{
  html: string;
  title: string;
}> {
  const submission = await prisma.formSubmission.findUnique({
    where: { id: formId },
    include: {
      template: true,
      permit: {
        include: {
          property: true,
        },
      },
    },
  });

  if (!submission) {
    throw new Error("Form submission not found");
  }

  const data = submission.data as Record<string, unknown>;
  const schema = submission.template.schema as {
    sections: {
      id: string;
      title: string;
      fields: {
        id: string;
        type: string;
        label: string;
        conditionalOn?: { field: string; value: unknown };
      }[];
    }[];
  };

  const title = `${submission.template.name} - ${submission.permit.title}`;

  // Build HTML
  let html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 30px;
      color: #1a1a1a;
      font-size: 12px;
      line-height: 1.5;
    }
    h1 {
      font-size: 20px;
      border-bottom: 2px solid #2563EB;
      padding-bottom: 8px;
      color: #111827;
    }
    h2 {
      font-size: 14px;
      color: #374151;
      margin-top: 24px;
      padding: 6px 0;
      border-bottom: 1px solid #E5E7EB;
    }
    .header-info {
      display: flex;
      justify-content: space-between;
      margin-bottom: 20px;
      font-size: 11px;
      color: #6B7280;
    }
    .field-row {
      display: flex;
      padding: 6px 0;
      border-bottom: 1px solid #F3F4F6;
    }
    .field-label {
      font-weight: 600;
      color: #374151;
      min-width: 200px;
    }
    .field-value {
      color: #1F2937;
      flex: 1;
    }
    .status-badge {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 4px;
      font-size: 11px;
      font-weight: 600;
    }
    .status-SUBMITTED { background: #DBEAFE; color: #1D4ED8; }
    .status-APPROVED { background: #D1FAE5; color: #065F46; }
    .status-DRAFT { background: #F3F4F6; color: #374151; }
    .footer {
      margin-top: 40px;
      padding-top: 16px;
      border-top: 1px solid #E5E7EB;
      font-size: 10px;
      color: #9CA3AF;
    }
  </style>
</head>
<body>
  <h1>${submission.template.name}</h1>
  <div class="header-info">
    <div>
      <strong>Permit:</strong> ${submission.permit.title}<br>
      <strong>Reference:</strong> ${submission.permit.internalRef}
    </div>
    <div>
      <strong>Status:</strong> <span class="status-badge status-${submission.status}">${submission.status}</span><br>
      <strong>Date:</strong> ${new Date(submission.updatedAt).toLocaleDateString()}
    </div>
  </div>
`;

  // Render each section and its fields
  for (const section of schema.sections) {
    html += `  <h2>${section.title}</h2>\n`;

    for (const field of section.fields) {
      // Skip conditionally hidden fields
      if (field.conditionalOn) {
        const depValue = data[field.conditionalOn.field];
        if (depValue !== field.conditionalOn.value) continue;
      }

      const value = data[field.id];
      let displayValue = "";

      if (value === undefined || value === null || value === "") {
        displayValue = '<em style="color: #9CA3AF;">Not provided</em>';
      } else if (typeof value === "boolean") {
        displayValue = value ? "Yes" : "No";
      } else if (Array.isArray(value)) {
        displayValue = value.join(", ");
      } else {
        displayValue = String(value);
      }

      html += `  <div class="field-row">
    <div class="field-label">${field.label}</div>
    <div class="field-value">${displayValue}</div>
  </div>\n`;
    }
  }

  html += `
  <div class="footer">
    Generated by Permits on the Go &bull; ${new Date().toLocaleString()}
  </div>
</body>
</html>`;

  return { html, title };
}
